# Generated by Django 4.2 on 2023-06-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.IntegerField(default=168, null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=5.8, max_digits=14)),
                ('outsourcing_costs', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('profit', models.IntegerField(default=25, null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_descriptions', models.TextField()),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_of_signing', models.DateField()),
                ('is_signed', models.BooleanField(default=False)),
                ('task_id', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='catalog.company')),
            ],
        ),
        migrations.CreateModel(
            name='PlannedBusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField(default=1)),
                ('staff_count', models.IntegerField(default=2)),
                ('lodging_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('public_transportation_fare', models.DecimalField(decimal_places=2, default=0, max_digits=14)),
                ('one_way_distance_on_company_transport', models.IntegerField(default=250, null=True)),
                ('locality', models.CharField(max_length=50)),
                ('budget_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_business_trips', to='commerce.budgetcalculation')),
            ],
        ),
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_descriptions', models.TextField()),
                ('service_delivery_period', models.IntegerField(default=168)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('crm_deal_id', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='catalog.company')),
                ('service_agreement', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='commerce.serviceagreement')),
                ('type_of_jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='catalog.typeofjobs')),
            ],
        ),
        migrations.AddField(
            model_name='budgetcalculation',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_calculations', to='commerce.commercialproposal'),
        ),
        migrations.AddField(
            model_name='budgetcalculation',
            name='type_of_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='catalog.typeofjobs'),
        ),
        migrations.CreateModel(
            name='AgreementStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_descriptions', models.TextField()),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('service_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_stages', to='commerce.serviceagreement')),
            ],
        ),
        migrations.CreateModel(
            name='ActOfCompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=20)),
                ('agreement_stage', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.agreementstage')),
                ('month_of_accounting_act_in_salary', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_in_salary', to='catalog.month')),
                ('month_signing_the_act', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_acts', to='catalog.month')),
                ('service_agreement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='commerce.serviceagreement')),
            ],
        ),
    ]
