# Generated by Django 4.2 on 2023-07-01 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_typeofjobs_options'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='actofcompletedwork',
            options={'verbose_name_plural': 'Acts of completed work'},
        ),
        migrations.AlterField(
            model_name='budgetcalculation',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=14),
        ),
        migrations.AlterField(
            model_name='budgetcalculation',
            name='type_of_jobs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='budget_calculations', to='catalog.typeofjobs'),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='service_delivery_period',
            field=models.IntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='service_descriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='total_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.RemoveField(
            model_name='commercialproposal',
            name='type_of_jobs',
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='commercialproposal',
            name='type_of_jobs',
            field=models.ManyToManyField(blank=True, null=True, related_name='commercial_proposals', to='catalog.typeofjobs'),
        ),
    ]
