# Generated by Django 4.2 on 2023-07-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceagreement',
            name='service_descriptions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
