# Generated by Django 4.2 on 2023-07-16 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0003_budgetcalculation_vat'),
    ]

    operations = [
        migrations.AddField(
            model_name='commercialproposal',
            name='proposal_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
