# Generated by Django 4.2 on 2023-07-01 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_month_year'),
        ('commerce', '0003_remove_commercialproposal_type_of_jobs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agreementstage',
            name='service_agreement',
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='act_status',
            field=models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=20),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='month_of_accounting_act_in_salary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_in_salary', to='catalog.month'),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='month_signing_the_act',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_acts', to='catalog.month'),
        ),
        migrations.DeleteModel(
            name='ActOfCompletedWork',
        ),
        migrations.DeleteModel(
            name='AgreementStage',
        ),
    ]
