# Generated by Django 4.2 on 2023-07-06 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_remove_agreementstage_service_agreement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceagreement',
            name='act_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='serviceagreement',
            name='agreement_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
