# Generated by Django 4.2 on 2023-07-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0004_commercialproposal_proposal_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetcalculation',
            name='calculation_file',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
