# Generated by Django 4.2 on 2023-07-08 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0005_serviceagreement_act_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetcalculation',
            name='profit',
            field=models.PositiveIntegerField(default=25, null=True),
        ),
        migrations.AlterField(
            model_name='budgetcalculation',
            name='workload',
            field=models.PositiveIntegerField(default=168, null=True),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='crm_deal_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commercialproposal',
            name='service_delivery_period',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.AlterField(
            model_name='plannedbusinesstrip',
            name='day_count',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='plannedbusinesstrip',
            name='one_way_distance_on_company_transport',
            field=models.PositiveIntegerField(default=250, null=True),
        ),
        migrations.AlterField(
            model_name='plannedbusinesstrip',
            name='staff_count',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
