# Generated by Django 4.2 on 2023-07-17 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commerce', '0006_budgetcalculation_profit_percentage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceagreement',
            name='number',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
