global:
  scrape_interval:     15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: flower
    static_configs:
      - targets: ['flower:5555']
  - job_name: django
    static_configs:
      - targets: ['app:8000']
  - job_name: nginx
    static_configs:
      - targets: [ 'nginx-exporter:9113' ]
  - job_name: node-exporter
    static_configs:
      - targets: [ 'node-exporter:9100' ]
  - job_name: cadvisor
    static_configs:
      - targets: [ 'cadvisor:8080' ]
  - job_name: postgres-exporter
    static_configs:
      - targets: ["postgres-exporter:9187"]