# Generated by Django 4.2 on 2023-06-24 19:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BudgetCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workload', models.IntegerField(null=True)),
                ('hourly_rate', models.DecimalField(decimal_places=2, max_digits=14)),
                ('outsourcing_costs', models.DecimalField(decimal_places=2, max_digits=14)),
                ('profit', models.IntegerField(null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
            ],
            options={
                'db_table': 'commerce_budget_calculation',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unp', models.IntegerField()),
                ('IBAN', models.CharField(max_length=28)),
                ('bank_name', models.CharField(max_length=30)),
                ('BIC', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'companies',
                'db_table': 'catalog_company',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'management_department',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('id_in_task_manager', models.CharField(max_length=36)),
                ('department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='job_manager_app.department')),
            ],
            options={
                'db_table': 'management_employee',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('count_of_working_days', models.IntegerField()),
                ('number_of_employees', models.FloatField()),
            ],
            options={
                'db_table': 'catalog_month',
            },
        ),
        migrations.CreateModel(
            name='TypeOfJobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'catalog_type_of_jobs',
            },
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_descriptions', models.TextField(blank=True, default=None)),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_of_signing', models.DateField()),
                ('is_signed', models.BooleanField(default=False)),
                ('task_id', models.IntegerField(null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='job_manager_app.company')),
            ],
            options={
                'db_table': 'commerce_service_agreement',
            },
        ),
        migrations.CreateModel(
            name='RegisteredAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=6)),
                ('locality', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=6)),
                ('office_number', models.CharField(max_length=6)),
                ('сompany', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_manager_app.company')),
            ],
            options={
                'db_table': 'catalog_registered_address',
            },
        ),
        migrations.CreateModel(
            name='PlannedBusinessTrip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_count', models.IntegerField()),
                ('staff_count', models.IntegerField()),
                ('lodging_cost', models.IntegerField(null=True)),
                ('public_transportation_fare', models.IntegerField(null=True)),
                ('one_way_distance_on_company_transport', models.IntegerField(null=True)),
                ('budget_calculation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planned_business_trips', to='job_manager_app.budgetcalculation')),
            ],
            options={
                'db_table': 'commerce_planned_business_trip',
            },
        ),
        migrations.CreateModel(
            name='MonthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_hours', models.FloatField()),
                ('status', models.CharField(choices=[('produced', 'produced'), ('planned', 'planned')], default='planned', max_length=20)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_manager_app.serviceagreement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_manager_app.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_manager_app.month')),
            ],
            options={
                'db_table': 'management_month_job',
            },
        ),
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='job_manager_app.employee')),
            ],
            options={
                'db_table': 'management_head_of_department',
            },
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='job_manager_app.headofdepartment'),
        ),
        migrations.CreateModel(
            name='CommercialProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_descriptions', models.TextField()),
                ('service_delivery_period', models.IntegerField(null=True)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=14)),
                ('crm_deal_id', models.IntegerField(blank=True, null=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='job_manager_app.company')),
                ('type_of_jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='commercial_proposals', to='job_manager_app.typeofjobs')),
            ],
            options={
                'db_table': 'commerce_commercial_proposal',
            },
        ),
        migrations.AddField(
            model_name='budgetcalculation',
            name='commercial_proposal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='budget_calculations', to='job_manager_app.commercialproposal'),
        ),
        migrations.AddField(
            model_name='budgetcalculation',
            name='type_of_jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='job_manager_app.typeofjobs'),
        ),
        migrations.CreateModel(
            name='BankBranchAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(max_length=6)),
                ('locality', models.CharField(max_length=50)),
                ('street', models.CharField(max_length=50)),
                ('house_number', models.CharField(max_length=6)),
                ('office_number', models.CharField(max_length=6)),
                ('сompany', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_manager_app.company')),
            ],
            options={
                'db_table': 'catalog_bank_branch_address',
            },
        ),
        migrations.CreateModel(
            name='AgreementStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_descriptions', models.TextField()),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('service_agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agreement_stages', to='job_manager_app.serviceagreement')),
            ],
            options={
                'db_table': 'commerce_agreement_stage',
            },
        ),
        migrations.CreateModel(
            name='ActOfCompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=20)),
                ('agreement_stage', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_manager_app.agreementstage')),
                ('month_of_accounting_act_in_salary', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_in_salary', to='job_manager_app.month')),
                ('month_signing_the_act', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_acts', to='job_manager_app.month')),
                ('service_agreement', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='job_manager_app.serviceagreement')),
            ],
            options={
                'db_table': 'commerce_act_of_completed_work',
            },
        ),
    ]
