# Generated by Django 4.1.7 on 2023-03-21 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ActOfCompletedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_number', models.IntegerField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('man_hours', models.FloatField()),
                ('status', models.CharField(choices=[('completed', 'completed'), ('not completed', 'not completed')], default='not completed', max_length=20)),
            ],
            options={
                'db_table': 'act_of_completed_work',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('unp', models.IntegerField()),
            ],
            options={
                'db_table': 'company',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Month',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('count_of_working_days', models.IntegerField()),
                ('number_of_employees', models.FloatField()),
            ],
            options={
                'db_table': 'month',
            },
        ),
        migrations.CreateModel(
            name='TypeOfJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
            ],
            options={
                'db_table': 'type_of_jobs',
            },
        ),
        migrations.CreateModel(
            name='ServiceAgreement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('date_of_signing', models.DateField()),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='job_manager_app.company')),
                ('type_of_jobs', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='job_manager_app.typeofjobs')),
            ],
            options={
                'db_table': 'service_agreement',
            },
        ),
        migrations.CreateModel(
            name='MonthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_hours', models.FloatField()),
                ('act', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_manager_app.actofcompletedwork')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_manager_app.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='job_manager_app.month')),
            ],
            options={
                'db_table': 'month_job',
            },
        ),
        migrations.AddField(
            model_name='actofcompletedwork',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='job_manager_app.serviceagreement'),
        ),
        migrations.AddField(
            model_name='actofcompletedwork',
            name='month_of_accounting_act_in_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_in_salary', to='job_manager_app.month'),
        ),
        migrations.AddField(
            model_name='actofcompletedwork',
            name='month_of_completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='job_manager_app.month'),
        ),
        migrations.AddField(
            model_name='actofcompletedwork',
            name='month_signing_the_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_acts', to='job_manager_app.month'),
        ),
        migrations.AddField(
            model_name='actofcompletedwork',
            name='responsible_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_of_employee', to='job_manager_app.employee'),
        ),
    ]
