# Generated by Django 4.1.7 on 2023-03-19 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceagreement',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='job_manager_app.company'),
        ),
        migrations.AlterField(
            model_name='serviceagreement',
            name='type_of_jobs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='agreements', to='job_manager_app.typeofjobs'),
        ),
    ]
