# Generated by Django 4.1.7 on 2023-03-21 14:20

from django.db import migrations
from django.core.management import call_command

from job_manager_app.apps import JobManagerAppConfig

fixture = f"../job_manager_extra_files/fixtures/dump.json"


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label=JobManagerAppConfig.name)

class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
