# Generated by Django 4.1.7 on 2023-03-21 14:20
from django.core.management import call_command
from django.db import migrations

from job_manager_app.apps import JobManagerAppConfig
from job_manager_app.migrations import fixtures


def load_fixture(apps, schema_editor):
    call_command('loaddata', *fixtures, app_label=JobManagerAppConfig.name)


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
