# Generated by Django 4.1.7 on 2023-03-19 11:20

from django.db import migrations
from django.core.management import call_command

from job_manager_app.apps import JobManagerAppConfig

fixture = f"/home/Alexandr/projects/job_manager_extra_files/fixtures/type_job.json"


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label=JobManagerAppConfig.name)


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0002_alter_serviceagreement_company_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]
