# Generated by Django 4.1.7 on 2023-03-19 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0003_auto_20230319_1120'),
    ]

    operations = [
        migrations.AddField(
            model_name='actofcompletedwork',
            name='month_of_accounting_act_in_salary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts_in_salary', to='job_manager_app.month'),
        ),
        migrations.AddField(
            model_name='actofcompletedwork',
            name='month_signing_the_act',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='signing_acts', to='job_manager_app.month'),
        ),
        migrations.AlterField(
            model_name='actofcompletedwork',
            name='agreement',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='job_manager_app.serviceagreement'),
        ),
        migrations.AlterField(
            model_name='actofcompletedwork',
            name='month_of_completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='job_manager_app.month'),
        ),
        migrations.AlterField(
            model_name='actofcompletedwork',
            name='responsible_employee',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='job_manager_app.employee'),
        ),
    ]
