# Generated by Django 4.1.7 on 2023-03-19 15:19

from django.db import migrations
from django.core.management import call_command

from job_manager_app.apps import JobManagerAppConfig

fixture = f"/home/Alexandr/projects/job_manager_extra_files/fixtures/months_2023.json"


def load_fixture(apps, schema_editor):
    call_command('loaddata', fixture, app_label=JobManagerAppConfig.name)




class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0004_actofcompletedwork_month_of_accounting_act_in_salary_and_more'),
    ]

    operations = [
        migrations.RunPython(load_fixture),
    ]

