# Generated by Django 4.1.7 on 2023-03-20 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('job_manager_app', '0006_alter_actofcompletedwork_month_of_completed_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actofcompletedwork',
            name='month_of_completed',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acts', to='job_manager_app.month'),
        ),
    ]
