# Generated by Django 4.2 on 2023-07-09 10:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commerce', '0001_initial'),
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthProxy',
            fields=[
            ],
            options={
                'verbose_name': 'MonthJob - Month',
                'verbose_name_plural': 'MonthJobs - Months',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('catalog.month',),
        ),
        migrations.CreateModel(
            name='ServiceAgreementProxy',
            fields=[
            ],
            options={
                'verbose_name': 'MonthJob - Agreement',
                'verbose_name_plural': 'MonthJobs - Agreements',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('commerce.serviceagreement',),
        ),
        migrations.CreateModel(
            name='MonthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_hours', models.FloatField()),
                ('status', models.CharField(choices=[('produced', 'produced'), ('planned', 'planned')], default='planned', max_length=20)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commerce.serviceagreement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='catalog.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='catalog.month')),
            ],
        ),
    ]
