# Generated by Django 4.2 on 2023-06-25 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('commerce', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=20)),
                ('patronymic', models.CharField(max_length=20)),
                ('rate', models.FloatField()),
                ('id_in_task_manager', models.CharField(blank=True, max_length=36)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='management.department')),
            ],
        ),
        migrations.CreateModel(
            name='MonthJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('man_hours', models.FloatField()),
                ('status', models.CharField(choices=[('produced', 'produced'), ('planned', 'planned')], default='planned', max_length=20)),
                ('agreement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='commerce.serviceagreement')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='management.employee')),
                ('month', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='catalog.month')),
            ],
        ),
        migrations.CreateModel(
            name='HeadOfDepartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heads', to='management.employee')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='head',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='management.headofdepartment'),
        ),
    ]
