# Generated by Django 4.2 on 2023-06-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='headofdepartment',
            options={'verbose_name_plural': 'Heads of departments'},
        ),
    ]
