version: '3.9'

services:
  postgres_db:
    image: postgres:15
    container_name: job_manager_db
    volumes:
      - ../job_manager_db:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - "${DB_OUT_PORT}:${DB_PORT}"
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRES_USER}" ]
      interval: 10s
      retries: 5

  web:
    build: .
    container_name: job_manager_app
    command: >
      bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8001:8000'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 256M
        reservations:
          cpus: '0.01'
          memory: 128M
    depends_on:
      postgres_db:
        condition: service_healthy
