FROM python:3.9
MAINTAINER Alex Maximchik 'alex@mail.ru'

SHELL ["/bin/bash", "-c"]

# set the environment variables
ENV PYTHONDONTWRITEBYTECODE 1 # no create cash
ENV PYTHONUNBUFFERED 1 # Force the stdout and stderr streams to be unbuffered

RUN pip install --upgrade pip
RUN useradd -rms /bin/bash job_manager && chmod 777 /opt /run

# mkdir + cd
WORKDIR /app

RUN chown -R job_manager:job_manager /app && chmod 755 /app

COPY --chown=job_manager . .

RUN pip install -r requirements.txt