version: '3.9'

services:
  mysql_db:
    image: mysql:5.7
    container_name: job_manager_db
    volumes:
      - ../mysql-data:/var/lib/mysql
      - ../mysql-logs:/var/log/mysql
    ports:
      - '3306:3306'
    env_file:
      - .env
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.01'
          memory: 256M

  web:
    build: .
    container_name: job_manager_app
    command: >
      bash -c "./manage.py migrate && ./manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - '8000:8000'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: 512M
        reservations:
          cpus: '0.01'
          memory: 256M
    depends_on:
      - mysql_db
