# Generated by Django 4.2 on 2023-06-30 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='typeofjobs',
            options={'verbose_name_plural': 'Types of jobs'},
        ),
    ]
