# Generated by Django 4.2 on 2023-07-01 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_alter_typeofjobs_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='month',
            name='year',
            field=models.PositiveIntegerField(editable=False, null=True),
        ),
    ]
